# Introduction to [Python](https://www.python.org/)

<img src="pics/python.png" alt="Python Logo" width="200">

Python is a high-level, interpreted programming language known for its readability and ease of use. It offers a broad range of applications, from web development and data analysis to machine learning and artificial intelligence. Python's extensive standard library and supportive community make it a great choice for both beginners and experienced developers.

## Table of Contents

* [Installation & Setup](#installation)
    * [Installing Python](#installpython)
    * [Installing Jupyter](#installjupyt)
    * [Running a Jupyter Notebook](#runjupyt)
    * [Using and Installing Visual Studio Code](#vscode)
    * [Packages](#packages)
* [Essentials](#essentials)
* [NumPy](#NumPy)
    * [Matrices (2D Arrays) in NumPy](#numpymatrix)
    * [Array Manipulation](#numpyarray)
* [Conditionals](#conditionals)
* [Control flow](#controlflow)
* [Comprehensions](#Comprehensions)

## Installation & Setup <a class="anchor" id="installation"></a>

### Installing Python <a class="anchor" id="installpython"></a>

`Windows & Mac`: Download the latest Python installer from [python.org](https://python.org/downloads/) and follow the installation instructions. Ensure to check the checkbox to add Python to the PATH during installation.

`Linux`: Python comes pre-installed on most distributions. If not, use the package manager for your distribution, e.g., sudo apt-get install python3 for Ubuntu.

Note: The Python installation comes with the `pip`, Python's package manager

### Installing Jupyter <a class="anchor" id="installjupyt"></a>

`Using pip`: Open a command prompt or terminal and run:

> pip install notebook

`Using Conda`: If you have Anaconda or Miniconda installed, run:

> conda install -c conda-forge notebook

### Running a Jupyter Notebook <a class="anchor" id="runjupyt"></a>

1. Open a terminal or command prompt.

2. Navigate to your project directory using `cd <directory_name>`.

3. Run the command `jupyter notebook` in the directory. A Jupyter dashboard will be created.

4. Open a new notebook from the Jupyter dashboard by clicking on `'New'` -> `'Python 3'`.

### Using and Installing Visual Studio Code <a class="anchor" id="vscode"></a>

Alternatively, instead of working directly in Jupyter notebooks, you can also import your Jupyter files into VS Code.

Download the installer from [Visual Studio Code](https://code.visualstudio.com/) and follow the installation instructions for your operating system.

Install the Jupyter extension by Microsoft from the extensions view

<img src="pics/jupyterext.png" alt="Python Logo" width="700">

### Installing Python Packages in Jupyter Notebook <a class="anchor" id="packages"></a>

Open a new cell in your Jupyter notebook.

Use the `%` symbol to run shell commands directly in the notebook. For example, to install `matplotlib`, type:

In [1]:
%pip install matplotlib


[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.




After installation, import the package in the notebook like any other Python module:


In [2]:
import matplotlib.pyplot as plt

- - - -

# Essentials <a class="anchor" id="essentials"></a>


- - - -

## Print
    
Print something in the console with print("something")

In [3]:
print("Hello world")

Hello world


- - - -


## Comments

In [4]:
# Single line comment

"""
Multi line comment
Multi line comment
Multi line comment
"""

'\nMulti line comment\nMulti line comment\nMulti line comment\n'

- - - -

## Variables

Create a variable and assign a value, like a = 5. Python is dynamically typed, which means it does not require explicit initialization.

In [5]:
a = 5

print(a)

print(type(a))

a = "Hello world"

print(type(a))

5
<class 'int'>
<class 'str'>


- - - -


## Basic Operations
    
    2+2 (Addition)
    2-2 (Subtraction)
    2*2 (Multiplication)
    2/2 (Division)
    2**2 (Potency)

In [6]:
2+2 #for example

4

- - - -

## Comparison operators
    
    a>b (Greater than)
    a<b (Less than)
    a==b (Equal to)
    a!=b (Not equal to)
    >= (Greater than or equal to)
    <= (Less than or equal to)

In [7]:
2 > 5 #for example

False

- - - -

## Incrementation and decrementation

In [8]:
a = 5

a += 1 #equal to a = a + 1

print(a)

a -= 1 #equal to a = a - 1

print(a)

6
5


- - - -

## Basic types in Python
    
    int (number without decimal point: 1)
    float (number with decimal point: 1.0 or 1.5)
    
    str (String: "Hello World!")
    list (ordered and mutable collection of items. Example: [1, 2, 3, 4, 5])
    
    bool (True or False)
    
    

In [9]:
print("\nType of 1 ") # \n for line break
print(type(1))

print("\nType of 1.0")
print(type(1.0))

print("\nType of 'Hello World!'")
print(type("Hello World!"))

print("\nType of [1, 2, 3, 4, 5]")
print(type([1, 2, 3, 4, 5]))

print("\nType of 'True'")
print(type(True))


Type of 1 
<class 'int'>

Type of 1.0
<class 'float'>

Type of 'Hello World!'
<class 'str'>

Type of [1, 2, 3, 4, 5]
<class 'list'>

Type of 'True'
<class 'bool'>


- - - -

## If - Else

    if condition:
        # code to execute if the condition is True
    else:
        # code to execute if the condition is False

In [10]:
a = 5

if (a > 5):
    print("a is bigger than five")
else:
    print("a is smaller than or equal to five")

a is smaller than or equal to five


- - - -

## For-Loop

The for loop in Python is a control flow statement that is used to repeatedly execute a block of statements as long as the condition is satisfied. It starts counting from 0.

    for variable in sequence:
        # code to be executed

In [11]:
for i in range(5): # 5 is exclusive
    print(i)

0
1
2
3
4


In [12]:
for i in range(4,7): # start is inclusive, end is exclusive
    print(i)

4
5
6


In [13]:
fruits = ["Apple", "Orange"] # create a list (also possible with np.array)

for fruit in fruits: # iterate trough the list
    print("I like this " + fruit)

I like this Apple
I like this Orange


- - - -

## Help

Writing '?' in front of a function name will display a help guide on this function

In [14]:
?sum

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

- - - -



# NumPy (Numerical Python) <a class="anchor" id="NumPy"></a>

NumPy, which stands for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for arrays (including multi-dimensional arrays), a large collection of mathematical functions and more. 

Python's built-in data structures like lists can handle many tasks, but they often fall short when dealing with large amounts of numerical data. This is where NumPy steps in.

Install NumPy: 
If you have installed Python through Anaconda, you should already have NumPy. 
Otherwise, install it in your console/shell with `pip install numpy` or directly in this notebook with:



In [15]:
%pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.



Once installed, you can import it into your Python scripts:

`import numpy as np` 

Note: `np` is a commonly used alias for numpy. This allows you to use the shorter `np` instead of writing out `numpy`. You have the freedom to select any alias you prefer, but adhering to conventional aliases is advised.
    
- - - -


In [16]:
import numpy as np

In [17]:
# Create a one-dimensional NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [18]:
# Also possible with variables
x = 12
y = 3

arr_2 = np.array([x, y])

print(arr_2)

[12  3]


In [19]:
# Create two arrays
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Elementwise Addition
arr_c = arr_a + arr_b

print(arr_c)

[5 7 9]


In [20]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Elementwise multiplication with constant
arr_d = arr_a * 2
print(arr_d)

# Elementwise multiplication with array
arr_e = arr_a * arr_b
print(arr_e)

[2 4 6]
[ 4 10 18]


- - - -

## Matrices (2D Arrays) in NumPy <a class="anchor" id="numpymatrix"></a>

In the context of NumPy, a matrix is a two-dimensional NumPy array. Matrices are an important part of many fields of science and engineering. With NumPy, you can create matrices, perform operations on them, and easily interface with libraries that use matrices in their computations.

You can create a matrix in NumPy by passing a list of lists to np.array(), where each list represents a row.

NumPy provides a variety of functions for performing operations on matrices. For example, you can add and subtract matrices, multiply them element-wise, and perform matrix multiplication.

- - - -


In [21]:
# Create matrices
matrix_a = np.array([[1, 2, 3], [3, 4, 5]]) #two-dimensional Numpy Array
matrix_b = np.array([[2, 3, 1], [1, 3, 2]]) #two-dimensional Numpy Array

print(matrix_a)

[[1 2 3]
 [3 4 5]]


#### Elementwise Addition

In [22]:
# Add matrices a and b
matrix_sum = matrix_a + matrix_b

print(matrix_sum)

[[3 5 4]
 [4 7 7]]


#### Elementwise Mulitplication

In [23]:
matrix_ew_multi = matrix_a * matrix_b # Element-Wise Multiplication

print(matrix_ew_multi)

[[ 2  6  3]
 [ 3 12 10]]


#### Matrix Multiplication

In [24]:
matrix_multi = np.dot(matrix_a.T, matrix_b) # Matrix Muliplication; T transposes/transforms matrix_a

# np.dot: the number of columns in the first matrix must
# be equal to the number of rows in the second matrix

print(matrix_multi)

[[ 5 12  7]
 [ 8 18 10]
 [11 24 13]]


#### Transpose Matrix with .T

In [25]:
print("Matrix A")
print(matrix_a)

print("\nMatrix A Transposed")
print(matrix_a.T)

Matrix A
[[1 2 3]
 [3 4 5]]

Matrix A Transposed
[[1 3]
 [2 4]
 [3 5]]


#### More

In [26]:
# Print out the shape
print(matrix_a.shape)

# Print out memory address
print(matrix_a.data)

# Print out the data type
print(matrix_a.dtype)

(2, 3)
int64


- - - -

## Array Manipulation <a class="anchor" id="numpyarray"></a>

When it comes to numerical computing or working with arrays, NumPy library (which provides the NumPy array data structure) is typically used due to its efficiency and the fact that it provides a lot of built-in functions designed for computations on arrays.


- - - -


In [27]:
# Create arr_1d and arr_2d

#one-dimensional Numpy Array (-> Array)
arr_1d = np.array([1, 2, 3, 4, 5, 6])   

#two-dimensional Numpy Array (-> Matrix)
arr_2d = np.array([[1,2,3],
                   [4,5,6]])    

#### Insert / Append

In [28]:
np.append(arr_1d, 5) # Append item 5 to the end

array([1, 2, 3, 4, 5, 6, 5])

In [29]:
np.append(arr_1d, [20,21,22]) # Also possible with multiple values (provided in a list)

array([ 1,  2,  3,  4,  5,  6, 20, 21, 22])

In [30]:
np.insert(arr_1d, 0, 5) # Insert item 5 to Index 0 (first element) 

array([5, 1, 2, 3, 4, 5, 6])

#### Delete

In [31]:
np.delete(arr_1d,0) # Delete item with Index 0 (first element)

array([2, 3, 4, 5, 6])

In [32]:
np.delete(arr_1d,-1) # Delete item with Index -1 (last element)

array([1, 2, 3, 4, 5])

In [33]:
np.delete(arr_1d,[0,1]) # Delete items with multiple indices

array([3, 4, 5, 6])

#### Concatenation

In [34]:
np.concatenate([arr_1d, arr_1d]) # 2x 1D Arrays provided as list to keep it as one input parameter 

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [35]:
# you can concatenate 2D Arrays vertically or horizontally

np.concatenate([arr_2d, arr_2d], axis=0)    # vertically: axis = 0


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
np.concatenate([arr_2d, arr_2d], axis=1)    # horizontally: axis = 1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### Subsetting Arrays

In [37]:
arr_1d[:] # Get whole array

array([1, 2, 3, 4, 5, 6])

In [38]:
arr_1d[0:2] # Return element 0 (incl.) to 2 (excl.)

array([1, 2])

In [39]:
arr_1d[:-1] # '-1': last element; '-2': 2nd last element; etc.

array([1, 2, 3, 4, 5])

In [40]:
arr_1d[0:4:2] # From index 1 to 4, return every 2nd output

array([1, 3])

#### Sum


In [41]:
np.sum(arr_2d) # sum is also a function of NumPy, that's why we use 'np.sum'

np.int64(21)

In [42]:
np.sum(arr_2d, axis=0) # 0. axis => vertical axis => operation across each column

array([5, 7, 9])

In [43]:
np.sum(arr_2d, axis=1) # 1. axis => horizontal axis => operation across each row

array([ 6, 15])

#### Vectorize / Map

Vectorizing or mapping refers to the process of applying a function to each element in an array or sequence, transforming the elements according to the rule defined by the function. In the provided example, the `add_five` function is vectorized using `np.vectorize`, allowing it to be applied to each element in `arr_1d`, effectively adding five to every element in the array.

In [44]:
arr_1d = np.array([1, 2, 3, 4, 5, 6]) 

# Define a simple function
def add_five(x):
    return x + 5

# Vectorize the function
vectorized_add_five = np.vectorize(add_five)

# Apply the function to the array
new_arr = vectorized_add_five(arr_1d) #matrix_a already exists

print(new_arr)

[ 6  7  8  9 10 11]


A lambda function in Python is a small, anonymous function defined with the keyword `lambda`. It is helpful as it allows defining a simple one-line function directly within the `np.vectorize` call, thereby eliminating the need for a separate, named function definition, making the code more concise and readable.

In [45]:
arr_1d = np.array([1, 2, 3, 4, 5, 6]) 

# Possible shorter with a lambda function

new_arr = np.vectorize(lambda x: x + 5)(arr_1d)

print(new_arr)

[ 6  7  8  9 10 11]


- - - - 

# Conditionals <a class="anchor" id="conditionals"></a>

Python supports "for-each" style loops with the syntax `for <variable> in <iterable>:`. It iterates through each item in the iterable, which can be a range, list, or other collection type. Note that the loop will iterate through all elements of the iterable.

In [46]:
# Example 1: Looping through a range
for i in range(1, 6):
    print(i)

1
2
3
4
5


In Python's `range()` function, the end of the range is exclusive, meaning `range(1, 6)` produces numbers 1 through 5.

In [47]:
# Example 2: Looping through a list
for i in [1.2, 2.3, 3.4, 4.5, 5.6]:
    print(i)

1.2
2.3
3.4
4.5
5.6


In the second example, the loop iterates through each number in the list, printing each value in turn.

- - - - 

# Control Flow <a class="anchor" id="controlflow"></a>



Python's control flow employs `if-elif-else` statements, with logical operators `or` and `and` used for logical comparisons. Indentation (whitespace) is used to denote code blocks under specific conditions.


In the example, a loop iterates through numbers from 0 to 12 (inclusive) with a step of 2. The `if-elif-else` conditions check the value of `i` during each iteration and print the corresponding statement.


In [48]:
# Example: Control Flow with Loop
for i in range(0, 13, 2):
    if i < 5:
        print(f"{i} is less than 5")
    elif i < 10:
        print(f"{i} is less than 10")
    else:
        if i == 10:
            print("the value is 10")
        else:
            print(f"{i} is bigger than 10")


0 is less than 5
2 is less than 5
4 is less than 5
6 is less than 10
8 is less than 10
the value is 10
12 is bigger than 10


- - - - 

# Comprehension <a class="anchor" id="comprehension"></a>

Python comprehensions provide a concise way to create lists, dictionaries, and sets using loops and conditionals. Note that Python uses zero-based indexing, meaning indexing starts from 0, which might affect how you define the range in comprehensions, especially when slicing or iterating through sequences.

List comprehensions and array comprehensions (using NumPy) have their own advantages. List comprehensions are often more syntactically straightforward and can be utilized without any additional imports. However, for numerical operations, NumPy array comprehensions may provide better performance due to its optimized numerical and mathematical operations, especially with larger data.


In [49]:
# Example 1: Basic List Comprehension
I = [i for i in range(1, 11)]

Here, `I` is a list of numbers from 1 to 10, inclusive. In Python, lists are versatile and can hold mixed types, but for mathematical operations, you might prefer using a NumPy array.


In [50]:
# Example 2: List Comprehension with Conditionals
I2 = [i for i in I if i % 2 != 1]

`I2` is created by filtering `I` to contain only even numbers, demonstrating the use of conditionals in comprehensions to filter values.


In [51]:
# Example 3: List Comprehension with Negative Conditionals
[i for i in I[:10] if i not in I2]

[1, 3, 5, 7, 9]

The final example, utilizing negative conditionals, generates a list of numbers from the first 10 elements of `I` that are not found in `I2`. Remember, the slicing `I[:10]` starts at index 0, so it returns the first 10 elements of `I`.

When dealing with numerical data and operations, using NumPy arrays might be advantageous due to their efficient memory usage and vectorized operations, which are typically faster than standard list operations, especially in computations involving large datasets.


#### List comprehension

In [52]:
squares = [x**2 for x in range(10)] # operator ** means potency

print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


#### List comprehension with condition


In [53]:
squares_3 = [x**2 for x in range(10) if x % 2 == 0] # ignore all uneven numbers in range(10) 

print(squares_3)

[0, 4, 16, 36, 64]


#### NumPy Array comprehension

In [54]:
squares_2 = np.array([x**2 for x in range(10)]) # same logic for arrays

print(squares_2)

[ 0  1  4  9 16 25 36 49 64 81]
